URL_TLD_BLACKLIST:
    # Government
    - .gov
    - .mil

    # China
    - .cn
    - ac.cn
    - ah.cn
    - bj.cn
    - com.cn
    - cq.cn
    - edu.cn
    - fj.cn
    - gd.cn
    - gov.cn
    - gs.cn
    - gx.cn
    - gz.cn
    - ha.cn
    - hb.cn
    - he.cn
    - hi.cn
    - hk.cn
    - hl.cn
    - hn.cn
    - jl.cn
    - js.cn
    - jx.cn
    - ln.cn
    - mo.cn
    - net.cn
    - nm.cn
    - nx.cn
    - org.cn
    - qh.cn
    - sc.cn
    - sd.cn
    - sh.cn
    - sn.cn
    - sx.cn
    - tj.cn
    - tw.cn
    - xj.cn
    - xz.cn
    - yn.cn
    - zj.cn