REDIS_SITES_HOST: 172.29.0.2
REDIS_SITES_PORT: 6379
REDIS_SITES_DB: 0
REDIS_SITES_PASS: devpassword

REDIS_TECHS_HOST: 172.29.0.2
REDIS_TECHS_PORT: 6379
REDIS_TECHS_DB: 1
REDIS_TECHS_PASS: devpassword